### ISSUE TITLE
Add convenience method on DTO.Thing to get container iid

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/COMET-SDK-Community-Edition#160]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

As part of the ["Acyclic Validation DerivedQuantityKind" issue](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/159) getting the container iid of a DTO Thing is needed in order to check for cycles. At @samatrhea's suggestion, this is currently done via getting all the objects of the container type and then manually checking and recreating the container "links" between objects.

This seems like the kind of information that should be available on the Thing or in a helper function (a candidate would be the Resolve service in the Server), if possible.

### Steps to Reproduce

NA

### System Configuration

- CDP4 Web Services version: 6.0.0
- CDP4JsonSerializer: 6.1.0

**Comment by samatrhea** [comment]
some thoughts on this issue:
  - we can add a property called ContainerIid to the Thing class, but this is not a part of 10-25 and will not be part of the serialization nor part of the Annex C REST API
  - the property can be set server side when a DTO is created based on data retreived from the database
  - the property does not have a lot of use client side, client side there is access to POCO's. It is important to note that due to this the property will have the value Guid.Empty and might cause some confusion for API developers. 

An alternative solution to have easy access to the unique identifier of a DTO (without adding a property to the Thing class) is to keep record of the containerIid for Each DTO in a service that is a wrapper around a Dictionary or ConcurrentDictionary. This service could be used to
  1 lookup the container of a DTO
  1 loopup all the containees of a DTO (reverse dictionary)

Let me know whether you think this could be a solution for the near future, adding data can be part of the code-generated ORM where the potential IContainerIdentifierMap is property injected and when the property is null we ignore it.

**Comment by cozminvelciu** [comment]
I think that adding a property on `DTO.Thing` that will only be present server-side, and `Guid.Empty` on the client will lead to unnecessary confusion.

In my opinion, having a service that can lookup the container for a given `DTO` would be better.

Regarding also adding the containees to this service, I don't think it's necessary, as as far as I remember, all DTOs have on them the property `ContainerLists` (as seen and inherited from `DTO.Thing`):
```
/// <summary>
/// Gets an <see cref="IEnumerable{IEnumerable}"/> that references the composite properties of the current <see cref="Thing"/>
/// </summary>
public virtual IEnumerable<IEnumerable> ContainerLists {
    ...
}
```

Additionally, since all the `iid`s of the contained `Thing`s are already present on the `DTO`, the already existing services can be used to retrieve them as `DTO`s themselves.

**Comment by samatrhea** [comment]
this will not be implemented
